import type {
  Alert,
  CanonicalEvent,
  Investigation,
  OperationalContext,
  Product,
  Stock,
} from "../lib/contracts";
export const time = "2026-01-01T12:00:00Z";
export const product: Product = {
  id: "product-1",
  sku: "CAM-001",
  name: "Câmera fictícia",
  description: null,
  price: null,
  gtin: null,
  category: "Demo",
  active: true,
  version: 0,
  createdAt: time,
  updatedAt: time,
};
export const stock: Stock = {
  sku: product.sku,
  expectedStock: 95,
  systemStock: 100,
  physicalStock: 93,
  systemUpdatedAt: time,
  physicalCountedAt: time,
  initialBaselineEventId: "baseline",
  baselineEventId: "baseline",
  checkpointEventId: "count",
  usedEventIds: ["baseline", "sale"],
};
export const sale: CanonicalEvent = {
  id: "sale",
  source: "demo-sales",
  externalEventId: "source-sale",
  type: "SALE_CONFIRMED",
  occurredAt: time,
  receivedAt: time,
  productId: product.id,
  sku: product.sku,
  externalProductId: "EXT-CAM",
  orderId: "1842",
  invoiceId: null,
  receiptId: null,
  movementId: null,
  quantity: 5,
  stockAfter: null,
  confirmed: false,
  metadata: {},
};
export const alert: Alert = {
  id: "alert-1",
  code: "E01",
  title: "Stock synchronization not confirmed",
  triggerEventId: sale.id,
  operationCommandId: null,
  status: "OPEN",
  severity: "CRITICAL",
  detectedAt: time,
  productId: product.id,
  sku: product.sku,
  orderId: sale.orderId,
  expectedState: "STOCK_UPDATED by deadline",
  observedState: "No correlated confirmation",
  ruleParameter: "timeoutSeconds=300",
  impact: "Process remains unconfirmed",
  recommendation: "Inspect attempts and retry",
  resolutionNote: null,
  resolvedAt: null,
  version: 0,
  evidence: [
    {
      id: "evidence-1",
      eventId: sale.id,
      type: "TRIGGER",
      source: sale.source,
      label: "Venda confirmada",
      value: "Pedido 1842",
      occurredAt: time,
    },
  ],
};
export function investigation(code: "E01" | "E02" = "E01"): Investigation {
  const count: CanonicalEvent = {
    ...sale,
    id: "count",
    type: "PHYSICAL_COUNT",
    source: "physical",
    externalProductId: null,
    quantity: 93,
    orderId: null,
    confirmed: true,
  };
  return {
    exception: { ...alert, code },
    trigger: code === "E02" ? count : sale,
    order: code === "E02" ? null : sale,
    stockAtDetection: { ...stock },
    currentStock: { ...stock, expectedStock: 93, baselineEventId: "count" },
    systemSnapshot: {
      ...sale,
      id: "baseline",
      type: "STOCK_UPDATED",
      source: "ERP",
      stockAfter: 100,
    },
    physicalCheckpoint: count,
  };
}
const execution = {
  commandId: null,
  channel: null,
  status: "NOT_AVAILABLE" as const,
  requestedAt: null,
  deadlineAt: null,
  lastAttemptAt: null,
  confirmedAt: null,
  attempts: [],
};
export const context: OperationalContext = {
  product,
  mappings: [],
  stock,
  inventorySync: execution,
  fiscalOrchestration: execution,
  exceptions: [],
  fiscal: {
    status: "UNKNOWN",
    documentId: null,
    source: null,
    confirmedAt: null,
    documentOccurredAt: null,
    evidenceEventId: null,
    commandId: null,
  },
};
