export type Tone = "success" | "warning" | "critical" | "processing" | "neutral";
export type Mapping = { channel: string; externalId: string; sku: string; status: "Ativo" | "Pendente"; lastSync: string };
export type Product = { id: string; name: string; sku: string; ean: string; initials: string; tint: string; mappingStatus: "Mapeado" | "Incompleto" | "Divergência"; mappings: Mapping[]; expected: number; erp: number; ml: number | null; shopee: number | null; physical: number | null };
export type Exception = { id: string; code: "E01" | "E02" | "E03" | "E04"; title: string; severity: "Crítica" | "Atenção"; status: "Aberta" | "Em análise" | "Resolvida"; productId?: string; orderId?: string; source: string; at: string; expected: string; observed: string; impact: string; rule: string; window: string; evidence: { time: string; title: string; source: string; detail: string; key: string; outcome: string }[]; jev?: { summary: string; hypothesis: string; confidence: string; action: string; alternatives: string[] }; retryable: boolean; resolutionNote?: string };
export type Order = { id: string; source: string; productId: string; quantity: number; at: string; inventory: string; fiscal: string; status: string };
export type Fiscal = { id: string; orderId: string; adapter: string; document: string; status: string; at: string };

export const initialProducts: Product[] = [
 { id:"CAM-001",name:"Camiseta Basic",sku:"CAM-001",ean:"7891234567801",initials:"CB",tint:"rose",mappingStatus:"Mapeado",expected:95,erp:95,ml:95,shopee:97,physical:94,mappings:[{channel:"ERP",externalId:"001238",sku:"CAM-BAS-P",status:"Ativo",lastSync:"16/09 · 14:32"},{channel:"Mercado Livre",externalId:"MLB2391872",sku:"CAM-BAS-P",status:"Ativo",lastSync:"16/09 · 14:31"},{channel:"Shopee",externalId:"SHOPEE-8821",sku:"CAM-BAS-P",status:"Ativo",lastSync:"16/09 · 14:21"}]},
 { id:"TEN-002",name:"Tênis Runner",sku:"TEN-002",ean:"7891234567802",initials:"TR",tint:"blue",mappingStatus:"Incompleto",expected:42,erp:42,ml:42,shopee:null,physical:42,mappings:[{channel:"ERP",externalId:"001245",sku:"TEN-002",status:"Ativo",lastSync:"16/09 · 13:50"},{channel:"Mercado Livre",externalId:"MLB31312",sku:"TEN-002",status:"Ativo",lastSync:"16/09 · 13:50"}]},
 { id:"MOC-003",name:"Mochila City",sku:"MOC-003",ean:"7891234567803",initials:"MC",tint:"lavender",mappingStatus:"Divergência",expected:27,erp:27,ml:null,shopee:29,physical:27,mappings:[{channel:"ERP",externalId:"005812",sku:"MOC-003",status:"Ativo",lastSync:"16/09 · 12:42"},{channel:"Shopee",externalId:"SHOPEE-7711",sku:"MOC-CITY",status:"Ativo",lastSync:"16/09 · 12:39"}]},
 { id:"BON-004",name:"Boné Snapback",sku:"BON-004",ean:"",initials:"BS",tint:"sand",mappingStatus:"Mapeado",expected:68,erp:68,ml:68,shopee:68,physical:68,mappings:[{channel:"ERP",externalId:"001277",sku:"BON-004",status:"Ativo",lastSync:"16/09 · 11:20"},{channel:"Mercado Livre",externalId:"MLB88217",sku:"BON-004",status:"Ativo",lastSync:"16/09 · 11:20"},{channel:"Shopee",externalId:"SHOPEE-0093",sku:"BON-004",status:"Ativo",lastSync:"16/09 · 11:20"}]},
 { id:"JAQ-005",name:"Jaqueta Wind",sku:"JAQ-005",ean:"7891234567805",initials:"JW",tint:"mint",mappingStatus:"Mapeado",expected:15,erp:15,ml:15,shopee:15,physical:15,mappings:[{channel:"ERP",externalId:"001289",sku:"JAQ-005",status:"Ativo",lastSync:"16/09 · 10:18"},{channel:"Mercado Livre",externalId:"MLB6721",sku:"JAQ-005",status:"Ativo",lastSync:"16/09 · 10:18"},{channel:"Shopee",externalId:"SHOPEE-3321",sku:"JAQ-005",status:"Ativo",lastSync:"16/09 · 10:18"}]},
 { id:"CAL-006",name:"Calça Cargo",sku:"CAL-006",ean:"7891234567806",initials:"CC",tint:"gray",mappingStatus:"Incompleto",expected:33,erp:33,ml:null,shopee:33,physical:null,mappings:[{channel:"ERP",externalId:"001298",sku:"CAL-006",status:"Ativo",lastSync:"16/09 · 09:44"},{channel:"Shopee",externalId:"SHOPEE-1181",sku:"CAL-006",status:"Ativo",lastSync:"16/09 · 09:44"}]}
];
export const initialExceptions: Exception[] = [
 {id:"EX-001",code:"E01",title:"Sincronização de estoque não confirmada",severity:"Crítica",status:"Aberta",productId:"CAM-001",orderId:"#1842",source:"Shopee",at:"16/09/2026 · 14:32",expected:"95 unidades após venda de 5",observed:"Shopee reporta 97 unidades; confirmação de 95 ausente",impact:"Risco de venda acima do estoque disponível no canal Shopee.",rule:"SALE_CONFIRMED → STOCK_UPDATED confirmado por canal",window:"5 minutos",retryable:true,evidence:[{time:"14:25",title:"SALE_CONFIRMED",source:"Mercado Livre",detail:"Pedido #1842 · CAM-001 · 5 unidades. Saldo anterior: 100.",key:"pedido-1842/CAM-001",outcome:"Recebido"},{time:"14:26",title:"Saldo esperado calculado",source:"PEEKio · estado derivado",detail:"100 − 5 = 95 unidades. Comando de sincronização criado para os canais.",key:"pedido-1842/CAM-001",outcome:"95 esperado"},{time:"14:27",title:"STOCK_UPDATED",source:"ERP e Mercado Livre",detail:"Os sistemas reportaram 95 unidades.",key:"pedido-1842/CAM-001",outcome:"Confirmado"},{time:"14:32",title:"Janela expirada",source:"Regra determinística E01",detail:"Nenhum STOCK_UPDATED de 95 unidades foi recebido da Shopee dentro de 5 minutos; último saldo reportado: 97.",key:"pedido-1842/CAM-001",outcome:"Evento esperado ausente"}],jev:{summary:"O canal Shopee não confirmou o saldo derivado da venda.",hypothesis:"O adapter pode ter recebido uma resposta incompleta ou a atualização do canal ainda não foi refletida.",confidence:"Alta prioridade de investigação",action:"Conferir o retorno do adapter e reprocessar a sincronização para Shopee.",alternatives:["Atraso no webhook de confirmação","Saldo alterado por operação concorrente"]}},
 {id:"EX-002",code:"E02",title:"Contagem física diverge do saldo esperado",severity:"Atenção",status:"Em análise",productId:"CAM-001",source:"Loja física",at:"16/09/2026 · 14:28",expected:"95 unidades",observed:"Contagem física: 94 unidades",impact:"Diferença de −1 unidade sujeita a nova conferência.",rule:"PHYSICAL_COUNT ≈ expected_stock",window:"Tolerância: 0 unidade",retryable:false,evidence:[{time:"14:26",title:"Saldo esperado calculado",source:"PEEKio",detail:"95 unidades a partir do último checkpoint e da venda confirmada.",key:"CAM-001",outcome:"95 esperado"},{time:"14:28",title:"PHYSICAL_COUNT",source:"Loja física",detail:"Contagem registrada de 94 unidades.",key:"CAM-001",outcome:"94 físico"},{time:"14:28",title:"Comparação determinística",source:"Regra E02",detail:"Diferença de −1 unidade acima da tolerância configurada de zero.",key:"CAM-001",outcome:"Divergência"}],jev:{summary:"A contagem difere em uma unidade do saldo derivado.",hypothesis:"A causa ainda não está comprovada. Pode haver movimentação sem registro ou erro de contagem.",confidence:"Hipótese a verificar",action:"Refazer a contagem e conferir movimentos recentes antes de ajustar o sistema.",alternatives:["Avaria ainda não registrada","Erro na contagem manual"]}},
 {id:"EX-003",code:"E03",title:"Saída física sem confirmação fiscal",severity:"Crítica",status:"Aberta",orderId:"#1842",source:"Sistema fiscal",at:"16/09/2026 · 14:18",expected:"INVOICE_ISSUED correlacionado ao pedido #1842",observed:"Nenhum documento confirmado após a janela configurada",impact:"Saída física sem evidência de documento fiscal confirmado.",rule:"PHYSICAL_EXIT → INVOICE_ISSUED",window:"10 minutos",retryable:true,evidence:[{time:"14:08",title:"PHYSICAL_EXIT",source:"Loja física",detail:"Saída de 2 unidades para pedido #1842.",key:"pedido-1842",outcome:"Recebido"},{time:"14:09",title:"Solicitação fiscal criada",source:"PEEKio → adapter fiscal",detail:"Comando enviado ao sistema fiscal responsável.",key:"pedido-1842",outcome:"Aguardando"},{time:"14:18",title:"Janela expirada",source:"Regra E03",detail:"INVOICE_ISSUED não recebido para o pedido dentro do prazo.",key:"pedido-1842",outcome:"Evento esperado ausente"}]},
 {id:"EX-004",code:"E04",title:"Quantidade recebida difere do registro",severity:"Atenção",status:"Aberta",productId:"MOC-003",source:"ERP",at:"16/09/2026 · 11:06",expected:"50 unidades recebidas fisicamente",observed:"47 unidades registradas no sistema",impact:"Diferença de −3 unidades no recebimento R100.",rule:"GOODS_RECEIVED → STOCK_UPDATED com quantidade correspondente",window:"Tolerância: 0 unidade",retryable:false,evidence:[{time:"10:58",title:"GOODS_RECEIVED",source:"Loja física",detail:"Recebimento R100 de 50 unidades de MOC-003.",key:"R100/MOC-003",outcome:"50 recebidas"},{time:"11:04",title:"STOCK_UPDATED",source:"ERP",detail:"Registro de entrada de 47 unidades vinculado ao recebimento R100.",key:"R100/MOC-003",outcome:"47 registradas"},{time:"11:06",title:"Comparação determinística",source:"Regra E04",detail:"Diferença de −3 unidades entre recebimento e registro.",key:"R100/MOC-003",outcome:"Divergência"}]},
 {id:"EX-005",code:"E01",title:"Sincronização anterior concluída",severity:"Atenção",status:"Resolvida",productId:"JAQ-005",source:"Mercado Livre",at:"15/09/2026 · 16:21",expected:"15 unidades",observed:"15 unidades após reprocessamento",impact:"Sem impacto ativo.",rule:"SALE_CONFIRMED → STOCK_UPDATED",window:"5 minutos",retryable:false,evidence:[{time:"16:21",title:"STOCK_UPDATED",source:"Mercado Livre",detail:"Saldo de 15 unidades confirmado após reprocessamento.",key:"JAQ-005",outcome:"Confirmado"}],resolutionNote:"Saldo conferido no canal."}
];
export const orders: Order[] = [
 {id:"#1842",source:"Mercado Livre",productId:"CAM-001",quantity:5,at:"16/09 · 14:25",inventory:"Falhou",fiscal:"Aguardando",status:"Atenção"},
 {id:"#1841",source:"Shopee",productId:"BON-004",quantity:1,at:"16/09 · 14:10",inventory:"Confirmado",fiscal:"Emitido",status:"Concluído"},
 {id:"#1840",source:"Loja online",productId:"TEN-002",quantity:2,at:"16/09 · 13:52",inventory:"Confirmado",fiscal:"Emitido",status:"Concluído"},
 {id:"#1839",source:"Shopee",productId:"JAQ-005",quantity:1,at:"16/09 · 10:18",inventory:"Confirmado",fiscal:"Processando",status:"Em andamento"}
];
export const fiscalOperations: Fiscal[] = [
 {id:"FIS-204",orderId:"#1842",adapter:"Fiscal mock",document:"—",status:"Falhou",at:"16/09 · 14:18"},
 {id:"FIS-203",orderId:"#1841",adapter:"Fiscal mock",document:"NF-00981",status:"Emitido",at:"16/09 · 14:12"},
 {id:"FIS-202",orderId:"#1840",adapter:"Fiscal mock",document:"NF-00980",status:"Emitido",at:"16/09 · 13:56"},
 {id:"FIS-201",orderId:"#1839",adapter:"Fiscal mock",document:"—",status:"Processando",at:"16/09 · 10:18"}
];
export const activities = [
 {time:"14:32",title:"Exceção de estoque criada",detail:"CAM-001 · Shopee",tone:"critical" as Tone},
 {time:"14:31",title:"Saldo confirmado",detail:"CAM-001 · Mercado Livre",tone:"success" as Tone},
 {time:"14:28",title:"Contagem física registrada",detail:"CAM-001 · Loja física",tone:"warning" as Tone},
 {time:"14:25",title:"Venda confirmada",detail:"Pedido #1842 · Mercado Livre",tone:"neutral" as Tone},
 {time:"14:12",title:"Documento fiscal confirmado",detail:"Pedido #1841 · Fiscal mock",tone:"success" as Tone}
];
